name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code from GitHub
      - uses: akhileshns/heroku-deploy@v3.12.12
        name: Build and Deploy Backend
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_BACKEND}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          appdir: "/Backend"
          docker_build_args: |
            MONGO_URI_ARG
            SERVICE_KEY_ARG
        env:
          MONGO_URI_ARG: ${{secrets.MONGO_URI}}
          SERVICE_KEY_ARG: ${{secrets.SERVICE_KEY}}
      - uses: akhileshns/heroku-deploy@v3.12.12
        name: Build and Deploy React App
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_FRONTEND}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          appdir: "/ReactApp"